### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bunder99** [TheDevFromKer/Telegram-CLI-Tools#1]
Hi! I tried to use your script and got the error. Below is what I did:

python addContact.py 
Adding from:
1 - file
2 - random generation
3 - 'brutoforce' numbers
Select: 2
From (ex. 150000000000): +10001000000 (as an example)
To (ex. 150099999999): +10001000999
Traceback (most recent call last):
  File "addContact.py", line 45, in <module>
    rndGenerator()
  File "addContact.py", line 30, in rndGenerator
    addNumber(randint(r0,r1))
  File "addContact.py", line 12, in addNumber
    telegram = Popen(["telegram-cli"], stdin=PIPE, stdout=sys.stdout)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Tlg-cli is installed and I logged in. I have 4.17.0-kali3-amd64.
What should I do? Please, help! Thanks in advance

**Comment by TheDevFromKer** [comment]
Run terminal and execute: telegram-cli If telegram-cli not opened - problem here. Or set full path to t-c.

**Comment by TheDevFromKer** [comment]
Connect to VPN if you ISP block Telegram and run script with sudo.
